### ISSUE TITLE
Crash on Kcauldron server when trying to view more than 1 camera with securitycraft.

### ISSUE THREAD

**Issue by InuYasha86000** [XCompWiz/LookingGlass#20]
this seems to be a server side issue as single player works perfect with more than 1 camera view. here is the error log:
[16:59:46] [Server thread/WARN] [LookingGlass/]: PacketHandler: Failed to handle packet type 10
[16:59:46] [Server thread/WARN] [LookingGlass/]: java.lang.NullPointerException
[16:59:46] [Server thread/WARN] [/]: java.lang.NullPointerException
[16:59:46] [Server thread/WARN] [/]:    at com.xcompwiz.lookingglass.network.packet.PacketChunkInfo.getMapChunkData(PacketChunkInfo.java:215)
[16:59:46] [Server thread/WARN] [/]:    at com.xcompwiz.lookingglass.network.packet.PacketChunkInfo.createPacket(PacketChunkInfo.java:51)
[16:59:46] [Server thread/WARN] [/]:    at com.xcompwiz.lookingglass.proxyworld.ChunkFinder.<init>(ChunkFinder.java:95)
[16:59:46] [Server thread/WARN] [/]:    at com.xcompwiz.lookingglass.network.packet.PacketCreateView.handle(PacketCreateView.java:73)
[16:59:46] [Server thread/WARN] [/]:    at com.xcompwiz.lookingglass.network.LookingGlassPacketManager.onPacketData(LookingGlassPacketManager.java:75)
[16:59:46] [Server thread/WARN] [/]:    at com.xcompwiz.lookingglass.network.LookingGlassPacketManager.onPacketData(LookingGlassPacketManager.java:63)
[16:59:46] [Server thread/WARN] [/]:    at cpw.mods.fml.common.eventhandler.ASMEventHandler_23_LookingGlassPacketManager_onPacketData_ServerCustomPacketEvent.invoke(.dynamic)
[16:59:46] [Server thread/WARN] [/]:    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[16:59:46] [Server thread/WARN] [/]:    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[16:59:46] [Server thread/WARN] [/]:    at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103)
[16:59:46] [Server thread/WARN] [/]:    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30)
[16:59:46] [Server thread/WARN] [/]:    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18)
[16:59:46] [Server thread/WARN] [/]:    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[16:59:46] [Server thread/WARN] [/]:    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[16:59:46] [Server thread/WARN] [/]:    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[16:59:46] [Server thread/WARN] [/]:    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[16:59:46] [Server thread/WARN] [/]:    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[16:59:46] [Server thread/WARN] [/]:    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[16:59:46] [Server thread/WARN] [/]:    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[16:59:46] [Server thread/WARN] [/]:    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[16:59:46] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
[16:59:46] [Server thread/WARN] [/]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[16:59:46] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[16:59:46] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[16:59:46] [Server thread/WARN] [/]:    at java.lang.Thread.run(Unknown Source)
[16:59:50] [Server thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$ServerTickEvent@2aa06406:
java.lang.NullPointerException
    at com.xcompwiz.lookingglass.network.packet.PacketChunkInfo.getMapChunkData(PacketChunkInfo.java:215) ~[PacketChunkInfo.class:?]
    at com.xcompwiz.lookingglass.network.packet.PacketChunkInfo.createPacket(PacketChunkInfo.java:51) ~[PacketChunkInfo.class:?]
    at com.xcompwiz.lookingglass.proxyworld.ChunkFinder.findChunks(ChunkFinder.java:137) ~[ChunkFinder.class:?]
    at com.xcompwiz.lookingglass.proxyworld.ChunkFinderManager.tick(ChunkFinderManager.java:24) ~[ChunkFinderManager.class:?]
    at com.xcompwiz.lookingglass.proxyworld.LookingGlassEventHandler.onServerTick(LookingGlassEventHandler.java:98) ~[LookingGlassEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_24_LookingGlassEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1566.UNOFFICIAL]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1566.UNOFFICIAL]
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251) [FMLCommonHandler.class:1.7.10-1566.UNOFFICIAL]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[16:59:50] [Server thread/ERROR] [FML/]: Index: 2 Listeners:
[16:59:50] [Server thread/ERROR] [FML/]: 0: NORMAL
[16:59:50] [Server thread/ERROR] [FML/]: 1: ASM: com.flansmod.common.CommonTickHandler@7519bb78 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[16:59:50] [Server thread/ERROR] [FML/]: 2: ASM: com.xcompwiz.lookingglass.proxyworld.LookingGlassEventHandler@552aee89 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[16:59:50] [Server thread/ERROR] [FML/]: 3: ASM: team.chisel.item.chisel.ChiselController@17eb27cf openQueuedGui(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[16:59:50] [Server thread/ERROR] [FML/]: 4: ASM: gcewing.lighting.GregsLighting@196dd701 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[16:59:50] [Server thread/ERROR] [FML/]: 5: ASM: codechicken.multipart.handler.MultipartEventHandler$@23d01b2d serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[16:59:50] [Server thread/ERROR] [FML/]: 6: ASM: com.rwtema.extrautils.CommandTPSTimer@1e821862 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[16:59:50] [Server thread/ERROR] [FML/]: 7: ASM: mrtjp.relocation.RelocationEventHandler$@21a93a9e serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[16:59:50] [Server thread/INFO] [me.ryanhamshire.GriefPrevention.GriefPrevention/]: [GriefPrevention] Disabling GriefPrevention v9.1
[16:59:50] [Server thread/INFO] [Minecraft/]: GriefPrevention: GriefPrevention disabled.
[16:59:50] [Server thread/INFO] [com.massivecraft.creativegates.CreativeGates/]: [CreativeGates] Disabling CreativeGates v2.7.4
[16:59:50] [Server thread/INFO] [/]: [CreativeGates 2.7.4] Disabled
[16:59:50] [Server thread/INFO] [com.onarandombox.MultiverseCore.MultiverseCore/]: [Multiverse-Core] Disabling Multiverse-Core v2.5-b708
[16:59:50] [Server thread/INFO] [com.massivecraft.massivecore.MassiveCore/]: [MassiveCore] Disabling MassiveCore v2.7.3
[16:59:50] [Server thread/INFO] [/]: [MassiveCore 2.7.3] Disabled
[16:59:50] [Server thread/INFO] [org.anjocaido.groupmanager.GroupManager/]: [GroupManager] Disabling GroupManager v2.1.31 (Phoenix)
[16:59:50] [Server thread/INFO] [com.sk89q.wepif.PermissionsResolverManager/]: WEPIF: GroupManager detected! Using GroupManager for permissions.
[16:59:50] [Server thread/INFO] [Minecraft/]: [Vault][Permission] GroupManager un-hooked.
[16:59:50] [Server thread/INFO] [Minecraft/]: [Vault][Chat] GroupManager - Chat un-hooked.
[16:59:50] [Server thread/INFO] [/]: GroupManager - INFO - Scheduled Data Saving is disabled!
[16:59:50] [Server thread/INFO] [/]: GroupManager version 2.1.31 (Phoenix) is disabled!
[16:59:50] [Server thread/INFO] [com.earth2me.essentials.spawn.EssentialsSpawn/]: [EssentialsSpawn] Disabling EssentialsSpawn v2.13.1
[16:59:50] [Server thread/INFO] [Essentials/]: Essentials: Using config file enhanced permissions.
[16:59:50] [Server thread/INFO] [Essentials/]: Permissions listed in as player-commands will be given to all users.
[16:59:50] [Server thread/INFO] [main.ChatColorPlugin/]: [ChatColor] Disabling ChatColor v2.1
[16:59:50] [Server thread/INFO] [net.milkbowl.vault.Vault/]: [Vault] Disabling Vault v1.4.1-b436
[16:59:50] [Server thread/INFO] [com.earth2me.essentials.Essentials/]: [Essentials] Disabling Essentials v2.13.1
[16:59:50] [Server thread/INFO] [de.Syranda.Timber.Plugin.Main/]: [Timber] Disabling Timber v1.3
[16:59:50] [Server thread/INFO] [com.sk89q.worldedit.bukkit.WorldEditPlugin/]: [WorldEdit] Disabling WorldEdit v5.6.3
[16:59:50] [Server thread/INFO] [NGT/]: can't write connected tran to nbt (train not found)
[16:59:50] [Server thread/INFO] [NGT/]: can't write connected tran to nbt (train not found)
[16:59:50] [Server thread/INFO] [NGT/]: can't write connected tran to nbt (train not found)
[16:59:50] [Server thread/INFO] [NGT/]: can't write connected tran to nbt (train not found)
[16:59:51] [Server thread/INFO] [FML/]: Unloading dimension 0
[16:59:51] [Server thread/INFO] [FML/]: Unloading dimension -1
[16:59:51] [Server thread/INFO] [FML/]: Unloading dimension 1
[16:59:51] [Server thread/INFO] [FML/]: Unloading dimension -42
[16:59:51] [Server thread/INFO] [FML/]: Unloading dimension -100
[16:59:51] [Server thread/INFO] [FML/]: Unloading dimension -112
[16:59:51] [Server thread/INFO] [FML/]: Applying holder lookups
[16:59:51] [Server thread/INFO] [FML/]: Holder lookups applied
[16:59:51] [Server thread/INFO] [FML/]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.

if there are any other log files you need let me know.

**Comment by XCompWiz** [comment]
Please use pastebin or text file uploads for future logs. Copy-pasting the log here makes it hard to read and takes up a lot of space.

If you are still experiencing this issue I'd like to have a log file of the occurrence. :)

**Comment by InuYasha86000** [comment]
I have actually moved onto using Thermos 1.7.10-1614, however it has a different issue with lookingglass.
The other open issue is here: https://github.com/CyberdyneCC/Thermos/issues/400

**Comment by InuYasha86000** [comment]
Thermos build 58 has fixed compatability with LookingGlass.

**Comment by XCompWiz** [comment]
If it works, then OK. :D
